const homeEditTxt = {
  heading: "Edit Home Page Content",
  firstNameLabel: "First Name",
  firstNamePlaceholder: "Enter first name",
  lastNameLabel: "Last Name",
  lastNamePlaceholder: "Enter last name",
  emailLabel: "Email",
  emailPlaceholder: "Enter email",
  phoneNumberLabel: "Phone Number",
  phoneNumberPlaceholder: "Enter phone number",
  profilePicUrlLabel: "Profile Picture URL",
  profilePicUrlPlaceholder: "Enter profile picture URL",
  resumeUrlLabel: "Resume URL",
  resumeUrlPlaceholder: "Enter resume URL",
  shortIntroLabel: "Short Introduction",
  shortIntroPlaceholder: "Enter a short introduction",
  taglineLabel: "Tagline",
  taglinePlaceholder: "Enter your tagline",
  socialMediaLinksLabel: "Social Media Links",
  socialMediaLinksOptional: "(optional)",
  addSocialLinkPlaceholder: "Add new social link",
  addSocialLinkBtn: "Add",
  noSocialLinks: "No social media links added.",
  saveBtn: "Save Changes",
  loadingBtn: "Saving...",
  removeSocialLinkAria: "Remove",
  fetchError: "Failed to fetch home details",
  updateSuccess: "Home details updated successfully!",
  updateError: "Failed to update home details",
};

export default homeEditTxt;
