const testimonialsEditTxt = {
  requiredField: "Name, description and image/video are required",
  projectName: "Project Name",
  projectNamePlaceholder: "Project Name",
  description: "Description",
  descriptionPlaceholder: "Description",
  problemSolve: "Problem Solved",
  problemSolvePlaceholder: "Problem Solved (optional)",
  techStack: "Tech Stack (optional)",
  techStackPlaceholder: "Comma separated (optional)",
  gitHubLink: "GitHub Link (optional)",
  gitHubLinkPlaceholder: "GitHub Link (optional)",
  liveLink: "Live Link (optional)",
  liveLinkPlaceholder: "Live Link (optional)",
  upload: "Upload Image or Video",
  edit: "Edit Testimonial",
  add: "Add Testimonial",
  save: "Save",
  cancel: "Cancel",
  delete: "Testimonial deleted successfully!",
  confirmDelete: "Are you sure you want to delete this testimonial?",
  confirmModalNote: "This action cannot be undone.",
  uploadSuccess: "File uploaded successfully.",
  uploadError: "Failed to upload file. Please try again.",
  fetchError: "Failed to fetch testimonials.",
  emptyList: "No testimonials yet.",
  altImageTxt: "Testimonial Image",
};

export default testimonialsEditTxt;
